In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("50_Startups.csv")

In [3]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset = pd.get_dummies(dataset, drop_first=True)
dataset = dataset.astype(int)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0
5,131876,99814,362861,156991,0,1
6,134615,147198,127716,156122,0,0
7,130298,145530,323876,155752,1,0
8,120542,148718,311613,152211,0,1
9,123334,108679,304981,149759,0,0
10,101913,110594,229160,146121,1,0
11,100671,91790,249744,144259,0,0
12,93863,127320,249839,141585,1,0
13,91992,135495,252664,134307,0,0
14,119943,156547,256512,132602,1,0
15,114523,122616,261776,129917,0,1
16,78013,121597,264346,126992,0,0
17,94657,145077,282574,125370,0,1
18,91749,114175,294919,124266,1,0
19,86419,153514,0,122776,0,1
20,76253,113867,298664,118474,0,0
21,78389,153773,299737,111313,0,1
22,73994,122782,303319,110352,1,0
23,67532,105751,304768,108733,1,0
24,77044,99281,140574,108552,0,1
25,64664,139553,137962,107404,0,0
26,75328,144135,134050,105733,1,0
27,72107,127864,353183,105008,0,1
28,66051,182645,118148,103282,1,0
29,65605,153032,107138,101004,0,1
30,61994,115641,91131,99937,1,0
31,61136,152701,88218,97483,0,1
32,63408,129219,46085,97427,0,0
33,55493,103057,214634,96778,1,0
34,46426,157693,210797,96712,0,0
35,46014,85047,205517,96479,0,1
36,28663,127056,201126,90708,1,0
37,44069,51283,197029,89949,0,0
38,20229,65947,185265,81229,0,1
39,38558,82982,174999,81005,0,0
40,28754,118546,172795,78239,0,0
41,27892,84710,164470,77798,1,0
42,23640,96189,148001,71498,0,0
43,15505,127382,35534,69758,0,1
44,22177,154806,28334,65200,0,0
45,1000,124153,1903,64926,0,1
46,1315,115816,297114,49490,1,0
47,0,135426,0,42559,0,0
48,542,51743,0,35673,0,1
49,0,116983,45173,14681,0,0

In [5]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [6]:
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend', 'State_Florida', 'State_New York']]

In [7]:
dependent = dataset[['Profit']]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size = 0.30, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler   #standardizing the data using the values of (mean, standard deviation formula)
sc=StandardScaler()
X_train = sc.fit_transform(X_train)             #fit method does only calcaulation, Where as transform will do the calculation and provides the final value 
X_test = sc.transform(X_test)

In [10]:
X_train

array([[ 1.17644918,  0.84516741,  0.94354831,  2.        , -0.76870611],
       [ 0.964209  ,  1.27283753,  0.42738466,  2.        , -0.76870611],
       [-1.47369376,  0.01533133, -1.52350767, -0.5       ,  1.30088727],
       [-1.48308111, -2.79556033, -1.53808904, -0.5       ,  1.30088727],
       [-0.14952413,  1.13638837, -0.71716479, -0.5       ,  1.30088727],
       [ 0.85311854, -0.04433364,  0.46771904, -0.5       ,  1.30088727],
       [-0.22353662, -0.31509692, -0.83981534,  2.        , -0.76870611],
       [-0.19455471,  0.21198893, -1.18497162, -0.5       , -0.76870611],
       [ 0.10479514, -0.08389031,  0.48741117, -0.5       , -0.76870611],
       [-1.00965537, -1.07020622, -0.40405994, -0.5       , -0.76870611],
       [ 0.06872149, -0.38396202,  0.75036622, -0.5       , -0.76870611],
       [-1.17639355,  0.14067823, -1.26581662, -0.5       ,  1.30088727],
       [ 0.97648634,  0.96892273,  0.84958544, -0.5       ,  1.30088727],
       [ 0.39131425,  0.45561766,  0.3979001 , -0.5       , -0.76870611],
       [-0.16881124,  0.6131456 , -0.48098184, -0.5       , -0.76870611],
       [ 1.20879249, -0.92948696,  1.24226335, -0.5       ,  1.30088727],
       [ 0.44593715,  0.82758236,  0.6270797 , -0.5       ,  1.30088727],
       [-0.9048368 , -0.20232741, -0.2140807 , -0.5       , -0.76870611],
       [-1.49419016, -0.26300168, -1.19195964, -0.5       , -0.76870611],
       [ 1.83846226,  1.07214274,  1.86319372, -0.5       , -0.76870611],
       [ 0.42966301,  0.13827145,  0.37625408,  2.        , -0.76870611],
       [-0.59093451, -2.81341712, -0.02839235, -0.5       , -0.76870611],
       [ 0.08493413, -0.95017754, -0.46096789, -0.5       ,  1.30088727],
       [ 1.26493212,  0.90991769, -0.55948984, -0.5       , -0.76870611],
       [-0.11002758, -0.69901791,  0.79713695,  2.        , -0.76870611],
       [-0.90670197,  0.1280232 ,  0.00300012,  2.        , -0.76870611],
       [ 0.11250179,  1.16515333,  0.75858788, -0.5       ,  1.30088727],
       [ 0.27708784,  1.15509918, -1.53808904, -0.5       ,  1.30088727],
       [ 1.03371228, -0.58535556,  0.79876902, -0.5       , -0.76870611],
       [-0.70389014, -1.58289019, -0.19719297, -0.5       , -0.76870611],
       [-1.4672374 , -0.30830358,  0.73848965,  2.        , -0.76870611],
       [ 1.46491545, -0.19747502,  1.39809935, -0.5       ,  1.30088727],
       [ 1.89486834,  0.51004205,  2.07686481, -0.5       ,  1.30088727],
       [-1.49419016,  0.45293914, -1.53808904, -0.5       , -0.76870611],
       [-1.03964159,  1.20525347, -1.32098523, -0.5       , -0.76870611]])

In [11]:
from sklearn.svm import SVR
regressor = SVR(kernel = "rbf", C=10)     #The "C" is known as parameter where number of error allowed to create a model
regressor.fit(X_train, Y_train)

#Kernal refers to the algorithm used to create a model in SVM (Support Vector Machine). 
#Types of algorithm - rbf (radial bias function), kernel{‘linear - Straight Line’, ‘poly - Parabola’, ‘rbf - Circle’, ‘sigmoid - S Shaped ’, ‘precomputed’} or callable, default=’rbf’

C:\Users\Sanjay\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=10)

In [12]:
regressor.intercept_

array([108733.51057129])

In [13]:
regressor.n_support_          #Verifying the number of support vectors (datapoints) used to create model

array([34], dtype=int32)

In [14]:
regressor.support_            #List of support vectors

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [15]:
y_pred = regressor.predict(X_test)

In [16]:
from sklearn.metrics import r2_score
r2_score = r2_score(Y_test, y_pred)

In [17]:
r2_score

-0.056814037652687555

In [21]:
from sklearn.svm import SVR
regressor = SVR(kernel = "poly", C=100)
regressor.fit(X_train, Y_train)

C:\Users\Sanjay\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100, kernel='poly')

In [22]:
y_pred = regressor.predict(X_test)

In [23]:
from sklearn.metrics import r2_score
r2_score = r2_score(Y_test, y_pred)
r2_score

-0.01980832469438143